# Generated by Django 4.2.2 on 2023-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterField(
            model_name='news_category',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
